# Generated by Django 6.0 on 2025-12-11 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('CollegeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('strength', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('PrincipalID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backendAPI.college')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendAPI.college')),
                ('subjects', models.ManyToManyField(to='backendAPI.subject')),
            ],
        ),
    ]
